name: Cleanup GHCR

on:
  schedule:
    - cron: "0 3 * * 0"  # Runs at 03:00 UTC every Sunday
  workflow_dispatch:     # Also allows manual triggering from the UI

jobs:
  cleanup-untagged-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Crucial: allows deleting packages via the GITHUB_TOKEN
    steps:
      - name: Delete all containers from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@707cf4f1445ec3e3f5c7bfc83a023fb868cd1174 # v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: user
